Repository kevin-lee/openai4s, pull requests merged in 2024-08, with the labels that each got.

#164 Remove dependency to refined4s-doobie
  build.sbt
Labels: pr

#165 openai4s v0.1.0-alpha10
  changelogs/0.1.0-alpha10.md
  version.sbt
Labels: pr, release

#166 Update: `version.sbt` - reset to `0.1.0-SNAPSHOT`
  version.sbt
Labels: pr

#167 Add Gpt4o-mini models
  modules/openai4s-core/shared/src/main/scala-2/openai4s/types/chat/Model.scala
  modules/openai4s-core/shared/src/main/scala-3/openai4s/types/chat/Model.scala
Labels: pr, include-in-release-note

#168 openai4s v0.1.0-alpha11
  changelogs/0.1.0-alpha11.md
  version.sbt
Labels: pr, release

#169 Update: `version.sbt` - reset to `0.1.0-SNAPSHOT`
  version.sbt
Labels: pr
